In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv(r'tips_data_encoded.csv')
data

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       1    4     1     2
1         10.34  1.66    1       1    4     1     3
2         21.01  3.50    1       1    4     1     3
3         23.68  3.31    1       1    4     1     2
4         24.59  3.61    0       1    4     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       1    3     1     3
240       27.18  2.00    0       0    3     1     2
241       22.67  2.00    1       0    3     1     2
242       17.82  1.75    1       1    3     1     2
243       18.78  3.00    0       1    1     1     2

[244 rows x 7 columns]

In [12]:
x = data.drop('tip',axis = 1)
y = data['tip']

In [13]:
x

total_bill  sex  smoker  day  time  size
0         16.99    0       1    4     1     2
1         10.34    1       1    4     1     3
2         21.01    1       1    4     1     3
3         23.68    1       1    4     1     2
4         24.59    0       1    4     1     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       1    3     1     3
240       27.18    0       0    3     1     2
241       22.67    1       0    3     1     2
242       17.82    1       1    3     1     2
243       18.78    0       1    1     1     2

[244 rows x 6 columns]

In [14]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [9]:
# training and testing
# 80% train
# 20% test

In [15]:
# split train test data
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42,test_size = 0.2)

# Model Training

In [17]:
data

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       1    4     1     2
1         10.34  1.66    1       1    4     1     3
2         21.01  3.50    1       1    4     1     3
3         23.68  3.31    1       1    4     1     2
4         24.59  3.61    0       1    4     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       1    3     1     3
240       27.18  2.00    0       0    3     1     2
241       22.67  2.00    1       0    3     1     2
242       17.82  1.75    1       1    3     1     2
243       18.78  3.00    0       1    1     1     2

[244 rows x 7 columns]

In [18]:
# import regressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor

In [42]:
# creating model
dt = DecisionTreeRegressor()
rf = RandomForestRegressor()
knn = KNeighborsRegressor()

In [33]:
# Train model
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [22]:
# it is ready to make predictions
dt.predict(x_test)

array([2.01, 1.32, 3.5 , 2.  , 2.  , 3.08, 5.  , 1.8 , 2.5 , 3.  , 3.  ,
       1.98, 2.  , 2.09, 1.25, 2.83, 3.76, 2.24, 2.3 , 7.58, 3.61, 4.06,
       2.2 , 1.25, 3.5 , 3.39, 2.5 , 4.29, 2.  , 6.73, 4.67, 1.  , 1.75,
       4.19, 1.01, 3.61, 2.2 , 4.73, 2.  , 3.48, 1.98, 2.5 , 3.31, 1.66,
       1.98, 1.  , 2.  , 3.  , 2.  ])

In [27]:
y_pred = dt.predict(x_test)
y_pred

array([2.01, 1.32, 3.5 , 2.  , 2.  , 3.08, 5.  , 1.8 , 2.5 , 3.  , 3.  ,
       1.98, 2.  , 2.09, 1.25, 2.83, 3.76, 2.24, 2.3 , 7.58, 3.61, 4.06,
       2.2 , 1.25, 3.5 , 3.39, 2.5 , 4.29, 2.  , 6.73, 4.67, 1.  , 1.75,
       4.19, 1.01, 3.61, 2.2 , 4.73, 2.  , 3.48, 1.98, 2.5 , 3.31, 1.66,
       1.98, 1.  , 2.  , 3.  , 2.  ])

In [25]:
#check the accuracy
from sklearn.metrics import r2_score

In [28]:
r_score_accuracy = r2_score(y_pred,y_test)
r_score_accuracy

0.33788645465715617

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor


In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 42 )

In [24]:
model_rf = RandomForestRegressor()
model_knn = KNeighborsRegressor()
model_dt = DecisionTreeRegressor()
model_rf.fit(x_train,y_train)
model_knn.fit(x_train,y_train)
model_dt.fit(x_train,y_train)


DecisionTreeRegressor()

In [44]:
model_rf.fit(x_train,y_train)


RandomForestRegressor()

In [45]:
model_knn.fit(x_train,y_train)


KNeighborsRegressor()

In [27]:
import joblib

In [28]:
joblib.dump(model_rf,'rf_trained.pkl')

['rf_trained.pkl']

In [30]:
joblib.dump(model_dt,'dt_trained.pkl')

['dt_trained.pkl']

In [31]:
joblib.dump(model_knn,'knn_trained.pkl')

['knn_trained.pkl']

In [34]:
dt.predict(x_test)

array([2.01, 4.  , 3.61, 2.  , 2.  , 3.08, 5.  , 1.8 , 2.5 , 3.48, 3.  ,
       1.98, 2.  , 2.09, 1.25, 2.83, 3.5 , 3.5 , 2.  , 7.58, 3.5 , 4.08,
       2.2 , 1.25, 3.5 , 3.39, 2.6 , 4.29, 2.  , 6.73, 4.67, 1.25, 1.75,
       4.19, 1.01, 3.61, 2.2 , 4.73, 2.  , 3.48, 1.98, 2.5 , 3.31, 1.66,
       1.98, 1.  , 2.  , 3.  , 2.  ])

In [35]:
y_pred = dt.predict(x_test)
y_pred

array([2.01, 4.  , 3.61, 2.  , 2.  , 3.08, 5.  , 1.8 , 2.5 , 3.48, 3.  ,
       1.98, 2.  , 2.09, 1.25, 2.83, 3.5 , 3.5 , 2.  , 7.58, 3.5 , 4.08,
       2.2 , 1.25, 3.5 , 3.39, 2.6 , 4.29, 2.  , 6.73, 4.67, 1.25, 1.75,
       4.19, 1.01, 3.61, 2.2 , 4.73, 2.  , 3.48, 1.98, 2.5 , 3.31, 1.66,
       1.98, 1.  , 2.  , 3.  , 2.  ])

In [36]:
from sklearn.metrics import r2_score

In [37]:
    r_score_accuracy = r2_score(y_pred,y_test)
    r_score_accuracy

0.3093313021015067

In [47]:
model_rf.fit(x_train,y_train)

RandomForestRegressor()

In [49]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [50]:
rf.predict(x_test)

array([2.647 , 2.5439, 3.7536, 3.3193, 1.9108, 3.2636, 4.4792, 1.7871,
       2.2858, 2.594 , 3.4019, 1.9807, 1.8267, 2.4616, 1.6767, 2.7987,
       3.1809, 3.9734, 2.672 , 6.4974, 3.4933, 3.4024, 2.4834, 1.9011,
       3.8545, 2.2543, 2.0876, 3.292 , 2.7232, 7.6123, 5.6138, 2.1707,
       2.4174, 3.4464, 2.0132, 3.9185, 1.9632, 4.7358, 1.9787, 3.4047,
       1.9142, 2.212 , 3.6188, 2.1399, 1.931 , 1.6654, 2.0044, 2.9841,
       1.9126])

In [51]:
y_pred = rf.predict(x_test)
y_pred

array([2.647 , 2.5439, 3.7536, 3.3193, 1.9108, 3.2636, 4.4792, 1.7871,
       2.2858, 2.594 , 3.4019, 1.9807, 1.8267, 2.4616, 1.6767, 2.7987,
       3.1809, 3.9734, 2.672 , 6.4974, 3.4933, 3.4024, 2.4834, 1.9011,
       3.8545, 2.2543, 2.0876, 3.292 , 2.7232, 7.6123, 5.6138, 2.1707,
       2.4174, 3.4464, 2.0132, 3.9185, 1.9632, 4.7358, 1.9787, 3.4047,
       1.9142, 2.212 , 3.6188, 2.1399, 1.931 , 1.6654, 2.0044, 2.9841,
       1.9126])

In [52]:
r_score_accuracy = r2_score(y_pred,y_test)
r_score_accuracy

0.36691596508615787

In [54]:
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [55]:
knn.predict(x_test)

array([2.884, 2.146, 3.978, 3.516, 2.234, 3.124, 4.684, 1.824, 2.218,
       2.888, 3.026, 2.07 , 1.772, 2.322, 1.846, 3.05 , 3.188, 3.824,
       2.562, 4.262, 3.33 , 2.78 , 2.358, 1.678, 3.476, 1.786, 1.678,
       2.992, 2.538, 6.346, 4.25 , 2.678, 2.928, 2.994, 2.364, 3.326,
       1.74 , 4.262, 1.896, 3.962, 1.988, 2.04 , 3.614, 2.228, 1.846,
       2.214, 2.448, 2.946, 1.63 ])

In [56]:
y_pred = knn.predict(x_test)
y_pred

array([2.884, 2.146, 3.978, 3.516, 2.234, 3.124, 4.684, 1.824, 2.218,
       2.888, 3.026, 2.07 , 1.772, 2.322, 1.846, 3.05 , 3.188, 3.824,
       2.562, 4.262, 3.33 , 2.78 , 2.358, 1.678, 3.476, 1.786, 1.678,
       2.992, 2.538, 6.346, 4.25 , 2.678, 2.928, 2.994, 2.364, 3.326,
       1.74 , 4.262, 1.896, 3.962, 1.988, 2.04 , 3.614, 2.228, 1.846,
       2.214, 2.448, 2.946, 1.63 ])

In [57]:
r_score_accuracy = r2_score(y_pred,y_test)
r_score_accuracy

0.04213811916506671